name: 'hotel_reservation'
version: '1.0.0'
config-version: 2

profile: 'hotel_reservation'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  hotel_reservation:
    staging:
      +schema: raw         
      +materialized: view  
    marts:
      +schema: analytics   
      +materialized: table 
